input {
  file {
    path                    => "/data/movies.ndjson"
    start_position          => "beginning"
    sincedb_path            => "/dev/null"
    codec                   => json
    mode                    => "read"
    file_completed_action   => "log"
    file_completed_log_path => "/tmp/movies-done.log"
  }
}

filter {
  mutate {
    remove_field => [ "@version", "event", "log", "host", "path" ]
  }

  mutate {
    convert => { "id" => "string" }
  }

  if [vote_average] {
    ruby {
      code => "event.set('user_score', event.get('vote_average').to_f)"
    }
  }

  if [release_date] == "" {
    mutate { remove_field => [ "release_date" ] }
  }

  if ![title] or [title] == "" {
    drop { }
  }
}

output {
  elasticsearch {
    hosts              => [ "${ES_HOST}" ]
    ssl_enabled         => false
    index              => "elastiflix-movies"
    document_id        => "%{id}"
    action             => "index"
    manage_template    => true
    template           => "/usr/share/logstash/templates/movies-template.json"
    template_name      => "elastiflix-movies"
    template_overwrite => true
  }
}
